openapi: 3.0.3
info:
  title: Pet Store API
  version: 1.0.0
  description: A simple Pet Store API for testing OpenAPI to FDSL transformation

servers:
  - url: https://api.petstore.example.com/v1

paths:
  /pets/{petId}:
    get:
      summary: Get pet by ID
      operationId: getPet
      parameters:
        - name: petId
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Pet found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Pet'
    put:
      summary: Update pet
      operationId: updatePet
      parameters:
        - name: petId
          in: path
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/PetUpdate'
      responses:
        '200':
          description: Pet updated
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Pet'
    delete:
      summary: Delete pet
      operationId: deletePet
      parameters:
        - name: petId
          in: path
          required: true
          schema:
            type: string
      responses:
        '204':
          description: Pet deleted

  /stores/{storeId}:
    get:
      summary: Get store by ID
      operationId: getStore
      parameters:
        - name: storeId
          in: path
          required: true
          schema:
            type: string
        - name: includeInventory
          in: query
          required: false
          schema:
            type: boolean
      responses:
        '200':
          description: Store found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Store'

  /orders/{orderId}:
    get:
      summary: Get order by ID
      operationId: getOrder
      parameters:
        - name: orderId
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Order found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Order'
    put:
      summary: Update order status
      operationId: updateOrder
      parameters:
        - name: orderId
          in: path
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/OrderUpdate'
      responses:
        '200':
          description: Order updated
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Order'

components:
  schemas:
    Pet:
      type: object
      required:
        - id
        - name
        - status
      properties:
        id:
          type: string
          readOnly: true
        name:
          type: string
        species:
          type: string
        age:
          type: integer
        status:
          type: string
        createdAt:
          type: string
          format: date-time
          readOnly: true
        updatedAt:
          type: string
          format: date-time
          readOnly: true

    PetUpdate:
      type: object
      properties:
        name:
          type: string
        species:
          type: string
        age:
          type: integer
        status:
          type: string

    Store:
      type: object
      required:
        - id
        - name
      properties:
        id:
          type: string
          readOnly: true
        name:
          type: string
        location:
          type: string
        inventoryCount:
          type: integer
          readOnly: true

    Order:
      type: object
      required:
        - id
        - petId
        - status
      properties:
        id:
          type: string
          readOnly: true
        petId:
          type: string
        quantity:
          type: integer
        status:
          type: string
        totalPrice:
          type: number
          readOnly: true
        createdAt:
          type: string
          format: date-time
          readOnly: true

    OrderUpdate:
      type: object
      required:
        - status
      properties:
        status:
          type: string
