version: "3.9"

networks:
  thesis_fdsl_net:
    external: true

services:
  dummyorders:
    build: .
    container_name: dummyorders
    ports:
      - "9100:9100"
    restart: unless-stopped
    networks:
      - thesis_fdsl_net

