version: "3.9"

networks:
  thesis_fdsl_net:
    external: true

services:
  dummyorders:
    image: node:20-alpine
    working_dir: /app
    container_name: dummyorders
    volumes:
      - .:/app
    command: ["node", "server.js"]
    ports:
      - "9100:9100"
    restart: unless-stopped
    networks:
      - thesis_fdsl_net

