version: "3.9"

networks:
  thesis_fdsl_net:
    external: true

services:
  dummyexternals:
    image: node:20-alpine
    container_name: dummyiot
    working_dir: /app
    command: ["node", "server.js"]
    volumes:
      - .:/app
    ports:
      - "9500:9500"
      - "9600:9600"
    restart: unless-stopped
    networks:
      - thesis_fdsl_net

