#!/bin/bash

echo "=========================================="
echo "Testing Orders API (v2 - Entity CRUD)"
echo "=========================================="

echo -e "\n1. LIST all orders"
curl -s http://localhost:8080/api/orders | jq

echo -e "\n2. GET single order (order-1)"
curl -s http://localhost:8080/api/orders/order-1 | jq

echo -e "\n3. CREATE new order"
echo "Request body:"
cat << 'EOF' | jq
{
  "userId": "user-123",
  "items": [
    {"productId": "prod-1", "quantity": 2, "price": 29.99},
    {"productId": "prod-2", "quantity": 1, "price": 49.99}
  ],
  "status": "pending"
}
EOF

echo -e "\nResponse:"
curl -s -X POST http://localhost:8080/api/orders \
  -H "Content-Type: application/json" \
  -d '{
    "userId": "user-123",
    "items": [
      {"productId": "prod-1", "quantity": 2, "price": 29.99},
      {"productId": "prod-2", "quantity": 1, "price": 49.99}
    ],
    "status": "pending"
  }' | jq

echo -e "\n4. UPDATE order status (order-1)"
echo "Request body:"
cat << 'EOF' | jq
{
  "userId": "user-456",
  "items": [
    {"productId": "prod-3", "quantity": 1, "price": 199.99}
  ],
  "status": "completed"
}
EOF

echo -e "\nResponse:"
curl -s -X PUT http://localhost:8080/api/orders/order-1 \
  -H "Content-Type: application/json" \
  -d '{
    "userId": "user-456",
    "items": [
      {"productId": "prod-3", "quantity": 1, "price": 199.99}
    ],
    "status": "completed"
  }' | jq

echo -e "\n5. LIST all orders (after update)"
curl -s http://localhost:8080/api/orders | jq

echo -e "\n6. DELETE order (order-2)"
echo "Status code:"
curl -s -o /dev/null -w "%{http_code}" -X DELETE http://localhost:8080/api/orders/order-2
echo ""

echo -e "\n7. GET deleted order (should be 404)"
echo "Status code:"
curl -s -o /dev/null -w "%{http_code}" http://localhost:8080/api/orders/order-2
echo ""

echo -e "\n8. LIST all orders (after delete)"
curl -s http://localhost:8080/api/orders | jq

echo -e "\n=========================================="
echo "TESTING NOTES:"
echo "=========================================="
echo "Notice how the CREATE request only includes:"
echo "  - userId, items, status (writable fields)"
echo ""
echo "The response includes computed fields:"
echo "  - id (auto-generated by backend)"
echo "  - createdAt (auto-generated timestamp)"
echo "  - itemCount (computed: len(items))"
echo "  - subtotal (computed: sum of item prices)"
echo "  - tax (computed: 10% of subtotal)"
echo "  - total (computed: subtotal + tax)"
echo ""
echo "=========================================="
echo "All tests complete!"
echo "=========================================="
