FROM python:3.11-slim

WORKDIR /app

# Install dependencies
RUN pip install --no-cache-dir flask flask-sock

# Copy dummy service
COPY dummy-service.py .

# Expose port
EXPOSE 9001

# Run service
CMD ["python", "dummy-service.py"]
