-- BYODB Schema Initialization for E-Commerce Example
-- This creates the users table expected by the ecommerce_byodb.fdsl configuration.
--
-- Run this after starting the PostgreSQL container:
--   docker exec -i ecommerce-byodb-db psql -U shop_admin -d ecommerce_shop < init_schema.sql
--
-- NOTE: Sessions table is auto-generated by FDSL - no need to create it here.

-- ============================================
-- Users Table: shop_users
-- ============================================
-- Maps to AuthDB columns:
--   id="email"           -> email column (login identifier)
--   password="password_hash" -> password_hash column (bcrypt)
--   role="user_role"     -> user_role column

CREATE TABLE IF NOT EXISTS shop_users (
    id SERIAL PRIMARY KEY,
    email VARCHAR(255) UNIQUE NOT NULL,
    password_hash VARCHAR(255) NOT NULL,
    user_role VARCHAR(50) NOT NULL DEFAULT 'customer',
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- Index for faster lookups by email
CREATE INDEX IF NOT EXISTS idx_shop_users_email ON shop_users(email);

-- ============================================
-- Test Users (Optional)
-- ============================================
-- Password for all test users: "password123"
-- bcrypt hash generated with: bcrypt.hashpw(b'password123', bcrypt.gensalt(rounds=12))

INSERT INTO shop_users (email, password_hash, user_role)
VALUES
    ('customer@shop.com', '$2b$12$AjCVj7DAsHgWcByYyuNtTOY3lfHTvURaXsfga2cIv19cZqqtPjheu', 'customer'),
    ('warehouse@shop.com', '$2b$12$AjCVj7DAsHgWcByYyuNtTOY3lfHTvURaXsfga2cIv19cZqqtPjheu', 'warehouse')
ON CONFLICT (email) DO NOTHING;

GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA public TO shop_admin;
GRANT ALL PRIVILEGES ON ALL SEQUENCES IN SCHEMA public TO shop_admin;
