version: "3.9"

networks:
  thesis_fdsl_net:
    external: true

services:
  dummydb:
    image: node:20-alpine
    working_dir: /app
    container_name: dummydb
    volumes:
      - .:/app
    command: ["node", "server.js"]
    ports:
      - "9000:9000"
    restart: unless-stopped
    networks:
      - thesis_fdsl_net
