version: "3.9"

networks:
  thesis_fdsl_net:
    external: true

services:
  dummydb:
    build: .
    container_name: dummydb
    ports:
      - "9000:9000"
    restart: unless-stopped
    networks:
      - thesis_fdsl_net
