FROM node:20-alpine

WORKDIR /app

# install dependencies
COPY package.json ./
COPY package-lock.json* pnpm-lock.yaml* bun.lockb* ./
RUN \
  if [ -f package-lock.json ]; then npm ci; \
  elif [ -f pnpm-lock.yaml ]; then npm i -g pnpm && pnpm i --frozen-lockfile; \
  else npm i; fi

# app source
COPY . .

RUN npm run postinstall

EXPOSE 5173

# SvelteKit dev server (works great in docker compose)
CMD ["npm", "run", "dev"]
