@startuml
set namespaceSeparator .



class model.FDSLModel  {
}


class utils.Import  {
  importURI : FQN
}


class entity.Attribute  {
  name : ID
  type : AttrType
  optional : optional<BOOL>
}


class entity.Input  {
  alias : ID
}


class entity.Entity  {
  name : ID
}


class entity.ValidationRule  {
}


class entity.Source <<abstract>> {
}


class entity.AuthBlock  {
  kind : STRING
  username : STRING
  password : STRING
  token : STRING
  key : STRING
  location : ApiKeyLoc
  value : STRING
}


class entity.SourceREST  {
  kind : STRING
  name : ID
  url : STRING
  verb : HttpVerb
}


class entity.SourceWS  {
  kind : STRING
  name : ID
  url : STRING
  protocol : STRING
}


class entity.APIEndpointREST  {
  kind : STRING
  name : ID
  path : STRING
  verb : HttpVerb
  summary : STRING
}


class entity.APIEndpointWS  {
  kind : STRING
  name : ID
  path : STRING
  summary : STRING
}


class entity.StringList  {
  items : list[STRING]
}


class entity.Header  {
  key : STRING
  value : STRING
}


class component.AttrRef  {
}


class component.Component <<abstract>> {
}


class component.TableComponent  {
  name : ID
}


class component.LineChartComponent  {
  name : ID
  seriesLabels : list[STRING]
  xLabel : STRING
  yLabel : STRING
}


class component.GaugeComponent  {
  name : ID
  min : FLOAT
  max : FLOAT
  label : STRING
  unit : STRING
}


class component.ActionFormComponent  {
  name : ID
  fields : list[ID]
  pathKey : ID
  submitLabel : STRING
}


class component.InputComponent  {
  name : ID
  label : optional<list[STRING]>
  placeholder : optional<list[STRING]>
  initial : optional<list[STRING]>
  submitLabel : optional<list[STRING]>
}


class component.LiveViewComponent  {
  name : ID
  label : optional<list[STRING]>
}


class server.Server  {
  name : ID
  host : STRING
  port : INT
  base : STRING
  cors : list[STRING]
  env : ID
  loglevel : ID
}


model.FDSLModel *--> "1..*" utils.Import: imports
model.FDSLModel *--> "1..*" server.Server: servers
model.FDSLModel *--> "1..*" entity.APIEndpointREST: apirest
model.FDSLModel *--> "1..*" entity.APIEndpointWS: apiws
model.FDSLModel *--> "1..*" entity.SourceREST: externalrest
model.FDSLModel *--> "1..*" entity.SourceWS: externalws
model.FDSLModel *--> "1..*" entity.Entity: entities
model.FDSLModel *--> "1..*" component.Component: components
entity.Input -->  entity.Entity: target
entity.Entity --> "1..*" entity.Entity: parents
entity.Entity --> "0..*" entity.Source: source
entity.Entity *--> "1..*" entity.Attribute: attributes
entity.Entity *--> "1..*" entity.ValidationRule: validations
entity.Source <|-- entity.APIEndpointREST
entity.Source <|-- entity.APIEndpointWS
entity.Source <|-- entity.SourceREST
entity.Source <|-- entity.SourceWS
entity.SourceREST -->  entity.Entity: entity
entity.SourceREST *--> "1..*" entity.Header: headers
entity.SourceREST *-->  entity.AuthBlock: auth
entity.SourceWS -->  entity.Entity: entity_in
entity.SourceWS -->  entity.Entity: entity_out
entity.SourceWS *-->  entity.StringList: subprotocols
entity.SourceWS *--> "1..*" entity.Header: headers
entity.SourceWS *-->  entity.AuthBlock: auth
entity.APIEndpointREST -->  entity.Entity: entity
entity.APIEndpointWS -->  entity.Entity: entity_in
entity.APIEndpointWS -->  entity.Entity: entity_out
entity.APIEndpointWS *-->  entity.AuthBlock: auth
component.AttrRef -->  entity.Attribute: attr
component.Component <|-- component.TableComponent
component.Component <|-- component.LineChartComponent
component.Component <|-- component.ActionFormComponent
component.Component <|-- component.GaugeComponent
component.Component <|-- component.InputComponent
component.Component <|-- component.LiveViewComponent
component.TableComponent -->  entity.APIEndpointREST: endpoint
component.TableComponent *-->  entity.StringList: colNames
component.LineChartComponent -->  entity.APIEndpointREST: endpoint
component.LineChartComponent *-->  component.AttrRef: rows
component.GaugeComponent -->  entity.APIEndpointWS: endpoint
component.GaugeComponent *-->  component.AttrRef: value
component.ActionFormComponent -->  entity.APIEndpointREST: endpoint
component.InputComponent -->  entity.APIEndpointWS: endpoint
component.LiveViewComponent -->  entity.APIEndpointWS: endpoint
component.LiveViewComponent *-->  entity.StringList: fields

legend
  Match rules:
  |= Name  |= Rule details |
  | ApiKeyLoc | header\|query |
  | FQN | ID (. ID)* |
  | Bool | true\|false |
  | AttrType | string\|int\|float\|number\|bool\|datetime\|uuid\|dict\|list |
  | AttrValue | STRING\|FLOAT\|INT |
  | HttpVerb | GET\|POST\|PUT\|DELETE\|PATCH |
  | Comment | \\/\\/[^\\n]* |
end legend

@enduml
