@startuml
set namespaceSeparator .



class model.FDSLModel  {
}


class utils.Import  {
  importURI : FQN
}


class entity.Attribute <<abstract>> {
}


class entity.SchemaAttribute  {
  name : ID
  type : AttrType
  optional : optional<BOOL>
  default : AttrValue
}


class entity.ComputedAttribute  {
  name : ID
  type : AttrType
  optional : optional<BOOL>
}


class entity.Input  {
  alias : ID
}


class entity.Entity  {
  name : ID
}


class entity.Source <<abstract>> {
}


class entity.ExternalRESTEndpoint  {
  name : ID
  url : STRING
  verb : HttpVerb
}


class entity.ExternalWSEndpoint  {
  name : ID
  url : STRING
  protocol : STRING
  subscribe : STRING
}


class entity.InternalRESTEndpoint  {
  name : ID
  verb : HttpVerb
  path : STRING
  summary : STRING
}


class entity.InternalWSEndpoint  {
  name : ID
  mode : WSmode
  path : STRING
  summary : STRING
}


class entity.StringList  {
  items : list[STRING]
}


class entity.Header  {
  key : STRING
  value : STRING
}


class component.AttrRef  {
}


class component.Component <<abstract>> {
}


class component.TableComponent  {
  name : ID
}


class component.LineChartComponent  {
  name : ID
  seriesLabels : list[STRING]
  xLabel : STRING
  yLabel : STRING
}


class component.GaugeComponent  {
  name : ID
  min : FLOAT
  max : FLOAT
  label : STRING
  unit : STRING
}


class component.ActionFormComponent  {
  name : ID
  fields : list[ID]
  pathKey : ID
  submitLabel : STRING
}


class component.PlotComponent  {
  name : ID
  xLabel : STRING
  yLabel : STRING
}


class server.Server  {
  name : ID
  host : STRING
  port : INT
  base : STRING
  cors : list[STRING]
  env : ID
}


model.FDSLModel *--> "1..*" utils.Import: imports
model.FDSLModel *--> "1..*" server.Server: servers
model.FDSLModel *--> "1..*" entity.InternalRESTEndpoint: internalrest
model.FDSLModel *--> "1..*" entity.InternalWSEndpoint: internalws
model.FDSLModel *--> "1..*" entity.ExternalRESTEndpoint: externalrest
model.FDSLModel *--> "1..*" entity.ExternalWSEndpoint: externalws
model.FDSLModel *--> "1..*" entity.Entity: entities
model.FDSLModel *--> "1..*" component.Component: components
entity.Attribute <|-- entity.ComputedAttribute
entity.Attribute <|-- entity.SchemaAttribute
entity.Input -->  entity.Entity: target
entity.Entity --> "1..*" entity.Entity: parents
entity.Entity -->  entity.Source: source
entity.Entity *--> "1..*" entity.Attribute: attributes
entity.Source <|-- entity.InternalRESTEndpoint
entity.Source <|-- entity.InternalWSEndpoint
entity.Source <|-- entity.ExternalRESTEndpoint
entity.Source <|-- entity.ExternalWSEndpoint
entity.ExternalRESTEndpoint *--> "1..*" entity.Header: headers
entity.ExternalRESTEndpoint -->  entity.Entity: entity
entity.ExternalWSEndpoint *-->  entity.StringList: subprotocols
entity.ExternalWSEndpoint *--> "1..*" entity.Header: headers
entity.ExternalWSEndpoint -->  entity.Entity: entity
entity.InternalRESTEndpoint -->  entity.Entity: entity
entity.InternalWSEndpoint -->  entity.Entity: entity
component.AttrRef -->  entity.Attribute: attr
component.Component <|-- component.TableComponent
component.Component <|-- component.LineChartComponent
component.Component <|-- component.ActionFormComponent
component.Component <|-- component.GaugeComponent
component.Component <|-- component.PlotComponent
component.TableComponent -->  entity.InternalRESTEndpoint: endpoint
component.TableComponent *-->  entity.StringList: colNames
component.LineChartComponent -->  entity.InternalRESTEndpoint: endpoint
component.LineChartComponent *-->  component.AttrRef: rows
component.GaugeComponent -->  entity.InternalWSEndpoint: endpoint
component.GaugeComponent *-->  component.AttrRef: value
component.ActionFormComponent -->  entity.InternalRESTEndpoint: endpoint
component.PlotComponent -->  entity.InternalRESTEndpoint: endpoint
component.PlotComponent *-->  component.AttrRef: x
component.PlotComponent *-->  component.AttrRef: y

legend
  Match rules:
  |= Name  |= Rule details |
  | HttpVerb | GET\|POST\|PUT\|DELETE\|PATCH |
  | AttrValue | STRING\|FLOAT\|INT |
  | Comment | \\/\\/[^\\n]* |
  | FQN | ID (. ID)* |
  | Bool | true\|false |
  | AttrType | string\|int\|float\|number\|bool\|datetime\|uuid\|dict\|list |
  | WSmode | publish\|subscribe |
end legend

@enduml
